"""Tests for idfpy model imports and basic functionality."""

from __future__ import annotations

import pytest


def test_version():
    from idfpy import __version__

    assert isinstance(__version__, str)
    assert __version__


def test_import_idf():
    from idfpy import IDF, IDFBaseModel

    idf = IDF()
    assert len(idf) == 0
    assert isinstance(idf, IDF)
    assert issubclass(IDFBaseModel, IDFBaseModel)


def test_import_zone():
    from idfpy.models import Zone

    zone = Zone(name='TestZone')
    assert zone.name == 'TestZone'
    assert zone.idf_object_type() == 'Zone'


def test_import_version():
    from idfpy.models import Version

    v = Version()
    assert v.version_identifier is not None


def test_import_building():
    from idfpy.models import Building

    b = Building()
    assert b.idf_object_type() == 'Building'


def test_model_registry():
    from idfpy.models import OBJECT_TYPE_REGISTRY, get_model_class

    assert 'Zone' in OBJECT_TYPE_REGISTRY
    assert 'Building' in OBJECT_TYPE_REGISTRY

    zone_cls = get_model_class('Zone')
    assert zone_cls is not None
    assert zone_cls.idf_object_type() == 'Zone'

    assert get_model_class('NonExistentType') is None


def test_field_order_registry():
    from idfpy.models import get_field_order

    zone_fields = get_field_order('Zone')
    assert isinstance(zone_fields, list)
    assert len(zone_fields) > 0
    assert 'name' in zone_fields

    assert get_field_order('NonExistentType') == []


def test_idf_base_model_config():
    from idfpy.models._base import IDFBaseModel

    config = IDFBaseModel.model_config
    assert config.get('populate_by_name') is True
    assert config.get('extra') == 'forbid'


def test_literal_case_normalization():
    """IDF files are case-insensitive; Literal fields should accept any case."""
    from idfpy.models import Building

    b = Building(north_axis=0.0, terrain='SUBURBS')  # ty: ignore[invalid-argument-type]
    assert b.terrain == 'Suburbs'


def test_idf_add_and_get():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    zone = Zone(name='Zone1')
    idf.add(zone)

    assert len(idf) == 1
    assert idf.get('Zone', 'Zone1') is zone
    assert idf.has('Zone', 'Zone1')
    assert not idf.has('Zone', 'Zone2')


def test_idf_add_duplicate_raises():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))

    with pytest.raises(ValueError, match='Duplicate'):
        idf.add(Zone(name='Z1'))


def test_idf_iter():
    from idfpy import IDF
    from idfpy.models import Building, Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Building())

    objects = list(idf)
    assert len(objects) == 2


def test_idf_all_of_type():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Zone(name='Z2'))

    zones = idf.all_of_type('Zone')
    assert len(zones) == 2
    assert 'Z1' in zones
    assert 'Z2' in zones


def test_to_idf_dict():
    from idfpy.models import Zone

    zone = Zone(name='TestZone', direction_of_relative_north=45.0)
    d = zone.to_idf_dict()
    assert d['name'] == 'TestZone'
    assert d['direction_of_relative_north'] == 45.0


def test_idf_save_and_load(tmp_path):
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    path = tmp_path / 'test.idf'
    idf.save(path)

    assert path.exists()
    content = path.read_text()
    assert 'Generated by idfpy' in content
    assert 'Zone' in content
    assert 'Office' in content

    loaded = IDF.load(path)
    assert len(loaded) >= 2
    assert loaded.has('Zone', 'Office')


def test_load_nonexistent_raises():
    from pathlib import Path

    from idfpy import IDF

    with pytest.raises(FileNotFoundError):
        IDF.load(Path('/nonexistent/file.idf'))


def test_ref_validator():
    from idfpy.models._refs import RefValidator

    v = RefValidator('ZoneNames')
    assert v('test') == 'test'
    assert v(None) is None
    assert v(123) == '123'
    assert 'ZoneNames' in repr(v)
