"""Tests for idfpy model imports and basic functionality."""

from __future__ import annotations

import pytest


def test_version():
    from idfpy import __version__

    assert isinstance(__version__, str)
    assert __version__


def test_import_idf():
    from idfpy import IDF, IDFBaseModel

    idf = IDF()
    assert len(idf) == 0
    assert isinstance(idf, IDF)
    assert issubclass(IDFBaseModel, IDFBaseModel)


def test_import_zone():
    from idfpy.models import Zone

    zone = Zone(name='TestZone')
    assert zone.name == 'TestZone'
    assert zone.idf_object_type() == 'Zone'


def test_import_version():
    from idfpy.models import Version

    v = Version()
    assert v.version_identifier is not None


def test_import_building():
    from idfpy.models import Building

    b = Building()
    assert b.idf_object_type() == 'Building'


def test_model_registry():
    from idfpy.models import OBJECT_TYPE_REGISTRY, get_model_class

    assert 'Zone' in OBJECT_TYPE_REGISTRY
    assert 'Building' in OBJECT_TYPE_REGISTRY

    zone_cls = get_model_class('Zone')
    assert zone_cls is not None
    assert zone_cls.idf_object_type() == 'Zone'

    assert get_model_class('NonExistentType') is None


def test_field_order_registry():
    from idfpy.models import get_field_order

    zone_fields = get_field_order('Zone')
    assert isinstance(zone_fields, list)
    assert len(zone_fields) > 0
    assert 'name' in zone_fields

    assert get_field_order('NonExistentType') == []


def test_idf_base_model_config():
    from idfpy.models._base import IDFBaseModel

    config = IDFBaseModel.model_config
    assert config.get('populate_by_name') is True
    assert config.get('extra') == 'forbid'


def test_literal_case_normalization():
    """IDF files are case-insensitive; Literal fields should accept any case."""
    from idfpy.models import Building

    b = Building(north_axis=0.0, terrain='SUBURBS')
    assert b.terrain == 'Suburbs'


def test_idf_add_and_get():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    zone = Zone(name='Zone1')
    idf.add(zone)

    assert len(idf) == 1
    assert idf.get('Zone', 'Zone1') is zone
    assert idf.has('Zone', 'Zone1')
    assert not idf.has('Zone', 'Zone2')


def test_idf_add_duplicate_raises():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))

    with pytest.raises(ValueError, match='Duplicate'):
        idf.add(Zone(name='Z1'))


def test_idf_iter():
    from idfpy import IDF
    from idfpy.models import Building, Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Building())

    objects = list(idf)
    assert len(objects) == 2


def test_idf_all_of_type():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Zone(name='Z2'))

    zones = idf.all_of_type('Zone')
    assert len(zones) == 2
    assert 'Z1' in zones
    assert 'Z2' in zones


def test_to_idf_dict():
    from idfpy.models import Zone

    zone = Zone(name='TestZone', direction_of_relative_north=45.0)
    d = zone.to_idf_dict()
    assert d['name'] == 'TestZone'
    assert d['direction_of_relative_north'] == 45.0


def test_idf_save_and_load(tmp_path):
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    path = tmp_path / 'test.idf'
    idf.save(path)

    assert path.exists()
    content = path.read_text()
    assert 'Generated by idfpy' in content
    assert 'Zone' in content
    assert 'Office' in content

    loaded = IDF.load(path)
    assert len(loaded) >= 2
    assert loaded.has('Zone', 'Office')


def test_load_nonexistent_raises():
    from pathlib import Path

    from idfpy import IDF

    with pytest.raises(FileNotFoundError):
        IDF.load(Path('/nonexistent/file.idf'))


def test_ref_validator():
    from idfpy.models._refs import RefValidator

    v = RefValidator('ZoneNames')
    assert v('test') == 'test'
    assert v(None) is None
    assert v(123) == '123'
    assert 'ZoneNames' in repr(v)


def test_to_dict():
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    d = idf.to_dict()

    # Version is unnamed → key should be "Version 1"
    assert 'Version 1' in d['Version']
    assert 'name' not in d['Version']['Version 1']

    # Zone is named → key should be the name value
    assert 'Office' in d['Zone']
    assert 'name' not in d['Zone']['Office']

    # Building has default name 'NONE'
    assert 'NONE' in d['Building']
    assert 'name' not in d['Building']['NONE']


def test_to_dict_preserves_empty_string_name():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='', direction_of_relative_north=15.0))

    d = idf.to_dict()

    assert '' in d['Zone']
    assert 'Zone 1' not in d['Zone']
    assert d['Zone']['']['direction_of_relative_north'] == 15.0

    loaded = IDF.from_dict(d)
    assert loaded.to_dict() == d


def test_to_dict_skips_existing_synthetic_name_keys():
    from idfpy import IDF
    from idfpy.models import ComfortViewFactorAngles

    idf = IDF()
    idf.add(ComfortViewFactorAngles(name='ComfortViewFactorAngles 1'))
    idf.add(ComfortViewFactorAngles(name='ComfortViewFactorAngles 2'))
    idf.add(ComfortViewFactorAngles())

    d = idf.to_dict()

    assert 'ComfortViewFactorAngles 1' in d['ComfortViewFactorAngles']
    assert 'ComfortViewFactorAngles 2' in d['ComfortViewFactorAngles']
    assert 'ComfortViewFactorAngles 3' in d['ComfortViewFactorAngles']


def test_from_dict():
    from idfpy import IDF

    data = {
        'Version': {'Version 1': {'version_identifier': '25.2'}},
        'Zone': {'TestZone': {'direction_of_relative_north': 0.0}},
    }
    idf = IDF.from_dict(data)

    assert idf.has('Zone', 'TestZone')
    zone = idf.get('Zone', 'TestZone')
    assert zone is not None
    assert zone.name == 'TestZone'  # ty: ignore[unresolved-attribute]
    assert zone.direction_of_relative_north == 0.0  # ty: ignore[unresolved-attribute]

    # Version has no name field, should still load
    assert len(idf.all_of_type('Version')) == 1


def test_epjson_roundtrip():
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0, terrain='Suburbs'))
    idf.add(Zone(name='Office', direction_of_relative_north=45.0))

    d = idf.to_dict()
    loaded = IDF.from_dict(d)

    assert loaded.has('Zone', 'Office')
    zone = loaded.get('Zone', 'Office')
    assert zone.direction_of_relative_north == 45.0  # ty: ignore[unresolved-attribute]

    building = loaded.get('Building', 'NONE')
    assert building is not None
    assert building.north_axis == 0.0  # ty: ignore[unresolved-attribute]
    assert building.terrain == 'Suburbs'  # ty: ignore[unresolved-attribute]


def test_epjson_save_load(tmp_path):
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    path = tmp_path / 'test.epjson'
    idf.save(path, output_type='epjson')
    assert path.exists()

    loaded = IDF.load(path)
    assert loaded.has('Zone', 'Office')
    assert len(loaded.all_of_type('Version')) == 1


def test_actual_idf_file(tmp_path):
    from pathlib import Path

    from idfpy import IDF

    idf = IDF.load(Path('./tests/test.idf'))
    dict_idf = idf.to_dict()
    loaded_idf = IDF.from_dict(dict_idf)
    assert len(idf) == len(loaded_idf)
