"""Tests for idfpy model imports and basic functionality."""

from __future__ import annotations

import pytest


def test_version():
    from idfpy import __version__

    assert isinstance(__version__, str)
    assert __version__


def test_import_idf():
    from idfpy import IDF, IDFBaseModel

    idf = IDF()
    assert len(idf) == 0
    assert isinstance(idf, IDF)
    assert issubclass(IDFBaseModel, IDFBaseModel)


def test_import_zone():
    from idfpy.models import Zone

    zone = Zone(name='TestZone')
    assert zone.name == 'TestZone'
    assert zone.idf_object_type() == 'Zone'


def test_import_version():
    from idfpy.models import Version

    v = Version()
    assert v.version_identifier is not None


def test_import_building():
    from idfpy.models import Building

    b = Building()
    assert b.idf_object_type() == 'Building'


def test_model_registry():
    from idfpy.models import OBJECT_TYPE_REGISTRY, get_model_class

    assert 'Zone' in OBJECT_TYPE_REGISTRY
    assert 'Building' in OBJECT_TYPE_REGISTRY

    zone_cls = get_model_class('Zone')
    assert zone_cls is not None
    assert zone_cls.idf_object_type() == 'Zone'

    assert get_model_class('NonExistentType') is None


def test_field_order_registry():
    from idfpy.models import get_field_order

    zone_fields = get_field_order('Zone')
    assert isinstance(zone_fields, list)
    assert len(zone_fields) > 0
    assert 'name' in zone_fields

    assert get_field_order('NonExistentType') == []


def test_idf_base_model_config():
    from idfpy.models._base import IDFBaseModel

    config = IDFBaseModel.model_config
    assert config.get('populate_by_name') is True
    assert config.get('extra') == 'forbid'


def test_literal_case_normalization():
    """IDF files are case-insensitive; Literal fields should accept any case."""
    from idfpy.models import Building

    b = Building(north_axis=0.0, terrain='SUBURBS')  # type: ignore
    assert b.terrain == 'Suburbs'


def test_idf_add_and_get():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    zone = Zone(name='Zone1')
    idf.add(zone)

    assert len(idf) == 1
    assert idf.get('Zone', 'Zone1') is zone
    assert idf.has('Zone', 'Zone1')
    assert not idf.has('Zone', 'Zone2')


def test_idf_add_duplicate_raises():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))

    with pytest.raises(ValueError, match='Duplicate'):
        idf.add(Zone(name='Z1'))


def test_idf_iter():
    from idfpy import IDF
    from idfpy.models import Building, Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Building())

    objects = list(idf)
    assert len(objects) == 2


def test_idf_all_of_type():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='Z1'))
    idf.add(Zone(name='Z2'))

    zones = idf.all_of_type('Zone')
    assert len(zones) == 2
    assert 'Z1' in zones
    assert 'Z2' in zones


def test_to_idf_dict():
    from idfpy.models import Zone

    zone = Zone(name='TestZone', direction_of_relative_north=45.0)
    d = zone.to_idf_dict()
    assert d['name'] == 'TestZone'
    assert d['direction_of_relative_north'] == 45.0


def test_idf_save_and_load(tmp_path):
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    path = tmp_path / 'test.idf'
    idf.save(path)

    assert path.exists()
    content = path.read_text()
    assert 'Generated by idfpy' in content
    assert 'Zone' in content
    assert 'Office' in content

    loaded = IDF.load(path)
    assert len(loaded) >= 2
    assert loaded.has('Zone', 'Office')


def test_load_nonexistent_raises():
    from pathlib import Path

    from idfpy import IDF

    with pytest.raises(FileNotFoundError):
        IDF.load(Path('/nonexistent/file.idf'))


def test_ref_validator():
    from idfpy.models._refs import RefValidator

    v = RefValidator('ZoneNames')
    assert v('test') == 'test'
    assert v(None) is None
    assert v(123) == '123'
    assert 'ZoneNames' in repr(v)


def test_to_dict():
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    d = idf.to_dict()

    # Version is unnamed → key should be "Version 1"
    assert 'Version 1' in d['Version']
    assert 'name' not in d['Version']['Version 1']

    # Zone is named → key should be the name value
    assert 'Office' in d['Zone']
    assert 'name' not in d['Zone']['Office']

    # Building has default name 'NONE'
    assert 'NONE' in d['Building']
    assert 'name' not in d['Building']['NONE']


def test_to_dict_preserves_empty_string_name():
    from idfpy import IDF
    from idfpy.models import Zone

    idf = IDF()
    idf.add(Zone(name='', direction_of_relative_north=15.0))

    d = idf.to_dict()

    assert 'Zone 1' in d['Zone']
    assert d['Zone']['Zone 1']['direction_of_relative_north'] == 15.0

    loaded = IDF.from_dict(d)
    assert loaded.to_dict() == d


def test_to_dict_skips_existing_synthetic_name_keys():
    from idfpy import IDF
    from idfpy.models import ComfortViewFactorAngles

    idf = IDF()
    idf.add(ComfortViewFactorAngles(name='ComfortViewFactorAngles 1'))
    idf.add(ComfortViewFactorAngles(name='ComfortViewFactorAngles 2'))
    idf.add(ComfortViewFactorAngles())

    d = idf.to_dict()

    assert 'ComfortViewFactorAngles 1' in d['ComfortViewFactorAngles']
    assert 'ComfortViewFactorAngles 2' in d['ComfortViewFactorAngles']
    assert 'ComfortViewFactorAngles 3' in d['ComfortViewFactorAngles']


def test_from_dict():
    from idfpy import IDF

    data = {
        'Version': {'Version 1': {'version_identifier': '25.2'}},
        'Zone': {'TestZone': {'direction_of_relative_north': 0.0}},
    }
    idf = IDF.from_dict(data)

    assert idf.has('Zone', 'TestZone')
    zone = idf.get('Zone', 'TestZone')
    assert zone is not None
    assert zone.name == 'TestZone'  # ty: ignore[unresolved-attribute]
    assert zone.direction_of_relative_north == 0.0  # ty: ignore[unresolved-attribute]

    # Version has no name field, should still load
    assert len(idf.all_of_type('Version')) == 1


def test_epjson_roundtrip():
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0, terrain='Suburbs'))
    idf.add(Zone(name='Office', direction_of_relative_north=45.0))

    d = idf.to_dict()
    loaded = IDF.from_dict(d)

    assert loaded.has('Zone', 'Office')
    zone = loaded.get('Zone', 'Office')
    assert zone.direction_of_relative_north == 45.0  # ty: ignore[unresolved-attribute]

    building = loaded.get('Building', 'NONE')
    assert building is not None
    assert building.north_axis == 0.0  # ty: ignore[unresolved-attribute]
    assert building.terrain == 'Suburbs'  # ty: ignore[unresolved-attribute]


def test_epjson_save_load(tmp_path):
    from idfpy import IDF
    from idfpy.models import Building, Version, Zone

    idf = IDF()
    idf.add(Version())
    idf.add(Building(north_axis=0.0))
    idf.add(Zone(name='Office'))

    path = tmp_path / 'test.epjson'
    idf.save(path, output_type='epjson')
    assert path.exists()

    loaded = IDF.load(path)
    assert loaded.has('Zone', 'Office')
    assert len(loaded.all_of_type('Version')) == 1


def test_rename_to_existing_name_raises():
    """Renaming an object to a name already taken by another object must raise."""
    from idfpy import IDF
    from idfpy.models.schedules import ScheduleCompact

    idf = IDF()
    idf.add(ScheduleCompact(name='Sched_A'))
    idf.add(ScheduleCompact(name='Sched_B'))

    sched_a = idf.get('Schedule:Compact', 'Sched_A')
    assert sched_a is not None
    with pytest.raises(ValueError, match='already exists'):
        sched_a.name = 'Sched_B'

    assert idf.get('Schedule:Compact', 'Sched_A') is sched_a
    assert idf.get('Schedule:Compact', 'Sched_B') is not sched_a


def test_add_nonstandard_provider_field_fluid_name():
    """FluidPropertiesName uses 'fluid_name' as provider; add() must index by it."""
    from idfpy import IDF
    from idfpy.models.fluids import FluidPropertiesName

    idf = IDF()
    obj = FluidPropertiesName(fluid_name='R410a', fluid_type='Refrigerant')
    idf.add(obj)

    assert idf.get('FluidProperties:Name', 'R410a') is obj
    assert obj._idf_obj_key == 'R410a'


def test_add_nonstandard_provider_field_coil_name():
    """AirflowNetworkDistributionComponentCoil uses 'coil_name' as provider."""
    from idfpy import IDF
    from idfpy.models.misc import AirflowNetworkDistributionComponentCoil

    idf = IDF()
    obj = AirflowNetworkDistributionComponentCoil(
        coil_name='MyCoil',
        coil_object_type='Coil:Cooling:DX:SingleSpeed',
        air_path_length=0.5,
        air_path_hydraulic_diameter=0.1,
    )
    idf.add(obj)

    assert idf.get('AirflowNetwork:Distribution:Component:Coil', 'MyCoil') is obj
    assert obj._idf_obj_key == 'MyCoil'


def test_add_nonstandard_provider_field_fan_name():
    """AirflowNetworkDistributionComponentFan uses 'fan_name' as provider."""
    from idfpy import IDF
    from idfpy.models.misc import AirflowNetworkDistributionComponentFan

    idf = IDF()
    obj = AirflowNetworkDistributionComponentFan(
        fan_name='MyFan',
        supply_fan_object_type='Fan:ConstantVolume',
    )
    idf.add(obj)

    assert idf.get('AirflowNetwork:Distribution:Component:Fan', 'MyFan') is obj
    assert obj._idf_obj_key == 'MyFan'


def test_provider_rename_from_none():
    """Setting a provider field from None to a value must update the index key."""
    from idfpy import IDF
    from idfpy.models.room_air import RoomAirNode

    idf = IDF()
    node = RoomAirNode(
        name=None,
        node_type='Control',
        zone_name='Zone1',
        height_of_nodal_control_volume_center=1.5,
    )
    idf.add(node)

    # Initially auto-keyed
    assert node._idf_obj_key == '_0'
    assert idf.get('RoomAir:Node', '_0') is node

    # Assign a real name
    node.name = 'MyNode'

    assert node._idf_obj_key == 'MyNode'
    assert idf.get('RoomAir:Node', 'MyNode') is node
    assert idf.get('RoomAir:Node', '_0') is None


def test_provider_rename_from_none_conflict_raises():
    """Renaming from None to an existing name must raise."""
    from idfpy import IDF
    from idfpy.models.room_air import RoomAirNode

    idf = IDF()
    idf.add(
        RoomAirNode(
            name='Existing',
            node_type='Control',
            zone_name='Zone1',
            height_of_nodal_control_volume_center=1.5,
        )
    )
    node2 = RoomAirNode(
        name=None,
        node_type='Floor',
        zone_name='Zone1',
        height_of_nodal_control_volume_center=0.0,
    )
    idf.add(node2)

    with pytest.raises(ValueError, match='already exists'):
        node2.name = 'Existing'


def test_actual_idf_file(tmp_path):
    from pathlib import Path

    from idfpy import IDF

    idf = IDF.load(Path('./tests/test.idf'))
    dict_idf = idf.to_dict()
    loaded_idf = IDF.from_dict(dict_idf)
    assert len(idf) == len(loaded_idf)


class TestPyiStub:
    def test_pyi_stub_exists(self):
        from pathlib import Path

        import idfpy.models as models_pkg

        pyi_path = Path(models_pkg.__file__).parent / '__init__.pyi'
        assert pyi_path.exists(), f'Missing type stub: {pyi_path}'

    def test_pyi_exports_match_all(self):
        import ast
        from pathlib import Path

        import idfpy.models as models_pkg

        pkg_dir = Path(models_pkg.__file__).parent
        pyi_tree = ast.parse((pkg_dir / '__init__.pyi').read_text())
        pyi_all: set[str] = set()
        for node in ast.walk(pyi_tree):
            if (
                isinstance(node, ast.Assign)
                and any(
                    isinstance(t, ast.Name) and t.id == '__all__' for t in node.targets
                )
                and isinstance(node.value, ast.List)
            ):
                pyi_all = {
                    elt.value
                    for elt in node.value.elts
                    if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                }

        missing = set(models_pkg.__all__) - pyi_all
        assert not missing, f'Missing from __init__.pyi __all__: {sorted(missing)}'
